[build]
  command = "cd apps/playground && pnpm build"
  publish = "apps/playground/.output/public"

[build.environment]
  NODE_VERSION = "20"
  PNPM_HOME = ".pnpm"
  PNPM_FLAGS = "--shamefully-hoist"
