[build]
  command = "turbo run build --filter playground"
  publish = "apps/playground/.output/public"

[build.environment]
  NODE_VERSION = "20"
  PNPM_HOME = ".pnpm"
  PNPM_FLAGS = "--shamefully-hoist"
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
