[build]
  command = "turbo run build --filter playground"
  publish = "apps/playground/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_BUILD_FROM_SOURCE = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
